### ISSUE TITLE
hsk launcher update error

### ISSUE THREAD

**Issue by halcyforn** [skyarkhangel/Hardcore-SK#2337]
from yesterday 03.08.2020 i get this error i cant autoupdate using hsk launcher manual work, english language error translated to " illegal characters in patch" idk why i dont update for 2 weeks and now this dont work anymore.. development branch and royality dlc

error log 

[2020.08.04 23:34:27][INFO][1][InstallerService] Download Path=C:\Users\user\AppData\Roaming\HSK-Launcher\Downloads\HSK-2020.08.04-19.36.36.zip 
[2020.08.04 23:34:27][INFO][1][InstallerService] Install Path=D:\Program Files (x86)\Steam\steamapps\common\RimWorld 
[2020.08.04 23:34:33][INFO][1][InstallerService] Step 2: Unpack. 
[2020.08.04 23:34:34][INFO][1][ArchiveService] Synchronizing installation 'D:\Program Files (x86)\Steam\steamapps\common\RimWorld'. 
[2020.08.04 23:34:34][WARN][1][Trace] Update failed. System.ArgumentException: Niedozwolone znaki w ścieżce. 
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.Combine(String path1, String path2)
   at HSKLauncher.Services.ArchiveService.<>c__DisplayClass8_0.<SynchronizeInstallation>b__0()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at HSKLauncher.Services.ArchiveService.<Unpack>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at HSKLauncher.Services.ArchiveService.<Unpack>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at HSKLauncher.Services.InstallerService.<InstallOnline>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at HSKLauncher.ViewModels.Pages.MainPageViewModel.<InstallUpdatesButton>d__39.MoveNext()

**Comment by AndreiAvinov** [comment]
Do you have all English letters in your path to Rimword exe file? It can sometimes break with some languages if path contains non-english letters

**Comment by halcyforn** [comment]
yes i have all english letters in patch to rimmworld.exe file . d:/Program files (x86)/steam/steamapps/common/rimworld the same for config folder only user name is halcyforn.000 this is user folder, but earlier all work , nothing change, idk why, only in game i get errors with informations like strange symbols but this can be becasue of royality dlc.
