### ISSUE TITLE
Игра регулярно падает c "mmap(PROT_NONE) failed"

### ISSUE THREAD

**Issue by l29ah** [skyarkhangel/Hardcore-SK#2374]
Есть core dump. Бектрейс:
```
#0  0x00007faf989bd331 in raise () at /lib64/libc.so.6
#1  0x00007faf989a6538 in abort () at /lib64/libc.so.6
#2  0x0000000000d46d74 in  ()
#3  0x00007faf91f8f70e in  () at /home/gamer/GOG Games/RimWorld/game/RimWorldLinux_Data/MonoBleedingEdge/x86_64/libmonobdwgc-2.0.so
#4  0x00007faf91f8f747 in  () at /home/gamer/GOG Games/RimWorld/game/RimWorldLinux_Data/MonoBleedingEdge/x86_64/libmonobdwgc-2.0.so
#5  0x00007faf98b55af0 in <signal handler called> () at /lib64/libpthread.so.0
#6  0x00007faf989bd331 in raise () at /lib64/libc.so.6
#7  0x00007faf989a6538 in abort () at /lib64/libc.so.6
#8  0x00007faf9207973e in GC_unmap () at /home/gamer/GOG Games/RimWorld/game/RimWorldLinux_Data/MonoBleedingEdge/x86_64/libmonobdwgc-2.0.so
#9  0x00007faf920797ab in GC_unmap_old () at /home/gamer/GOG Games/RimWorld/game/RimWorldLinux_Data/MonoBleedingEdge/x86_64/libmonobdwgc-2.0.so
#10 0x00007faf9207c6ab in GC_finish_collection () at /home/gamer/GOG Games/RimWorld/game/RimWorldLinux_Data/MonoBleedingEdge/x86_64/libmonobdwgc-2.0.so
#11 0x00007faf9207c914 in GC_collect_a_little_inner () at /home/gamer/GOG Games/RimWorld/game/RimWorldLinux_Data/MonoBleedingEdge/x86_64/libmonobdwgc-2.0.so
#12 0x00007faf9207cd82 in GC_allocobj () at /home/gamer/GOG Games/RimWorld/game/RimWorldLinux_Data/MonoBleedingEdge/x86_64/libmonobdwgc-2.0.so
#13 0x00007faf9207dbb4 in GC_generic_malloc_inner () at /home/gamer/GOG Games/RimWorld/game/RimWorldLinux_Data/MonoBleedingEdge/x86_64/libmonobdwgc-2.0.so
#14 0x00007faf92080a2c in GC_generic_malloc () at /home/gamer/GOG Games/RimWorld/game/RimWorldLinux_Data/MonoBleedingEdge/x86_64/libmonobdwgc-2.0.so
#15 0x00007faf92080c94 in GC_malloc_kind_global () at /home/gamer/GOG Games/RimWorld/game/RimWorldLinux_Data/MonoBleedingEdge/x86_64/libmonobdwgc-2.0.so
#16 0x00007faf92053ef2 in  () at /home/gamer/GOG Games/RimWorld/game/RimWorldLinux_Data/MonoBleedingEdge/x86_64/libmonobdwgc-2.0.so
#17 0x00007faf9200b132 in  () at /home/gamer/GOG Games/RimWorld/game/RimWorldLinux_Data/MonoBleedingEdge/x86_64/libmonobdwgc-2.0.so
#18 0x00007faf9201e11e in  () at /home/gamer/GOG Games/RimWorld/game/RimWorldLinux_Data/MonoBleedingEdge/x86_64/libmonobdwgc-2.0.so
#19 0x0000000040c2f426 in  ()
#20 0x0000000000000000 in  ()
```

**Comment by skyarkhangel** [comment]
Нужен лог от игры, найти можно тут
/home/your user name/.config/unity3d/Ludeon Studios/RimWorld/

**Comment by l29ah** [comment]
Похоже, проблема во взаимодействии mono c linux.
https://xamarin.github.io/bugzilla-archives/62/6216/bug.html

>  Something different about the garbage collector was causing more unmappings than before so we were blowing past the default application limit, which on our version of ubuntu was set to 65535. We increased that 10 fold and haven't seen the problem since.

> So now we have:
> vm.max_map_count = 655360

Поставил столько, пока что не падает.
